### ISSUE TITLE
Issue with running main.py

### ISSUE THREAD

**Issue by AkshDesai04** [hitarthdesai/file-systems-manager#2]
Hey, I tried running main.py by using the following command `python main.py`.
It didn't compile properly and has given the following error
  
  
>Traceback (most recent call last):  
>  File "C:\Users\Aksh Desai\Code\file-systems-manager\main.py", line 2, in <module>  
>    from ui import createVerticalFrame  
>  File "C:\Users\Aksh Desai\Code\file-systems-manager\ui.py", line 2, in <module>  
>    from actions import addFileHandler, removeFilesHandler, addWidget, manageMonitor  
>  File "C:\Users\Aksh Desai\Code\file-systems-manager\actions.py", line 3, in <module>  
>    from globals import files, frames, downloadsPath, removalTexts, monitor, buttons, monitorTexts, downloadsObserver, folderName, createFoldersButton, titles  
>  File "C:\Users\Aksh Desai\Code\file-systems-manager\globals.py", line 41, in <module>  
>    from watchdog.observers import Observer  
>ModuleNotFoundError: No module named 'watchdog'  
  
  
The issue seems to be from the `globals.py` file from line 41 "`from watchdog.observers import Observer`"  
Seems like it might be a naming conflict

**Comment by hitarthdesai** [comment]
Did you install watchdog for python3 using
`pip3 install watchdog`?

If you already did once, try removing watchdog and installing it again.

**Comment by AkshDesai04** [comment]
My bad.
Works perfectly after the pip install
Tx :)
